version: "3"

services:
  mariadb-server:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      - MARIADB_DATABASE=project
      - MARIADB_ROOT_PASSWORD=super-secret-password
      - MARIADB_USER=super-user
      - MARIADB_PASSWORD=super-password
    volumes:
      - maria-db:/var/lib/mysql
    networks:
      - app-network

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: project/backend
    container_name: backend-api
    networks:
      - app-network
    depends_on:
      - mariadb-server

  frontend-api:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: project/frontend
    container_name: frontend-api
    networks:
      - app-network
    depends_on:
      - backend-api
    ports:
      - 3000:8080

volumes:
  maria-db:
    name: "mongo-db"

networks:
  app-network:
    name: app-network
